export const ICD10_CODES = [
    { code: 'A00.0', desc: 'Cholera due to Vibrio cholerae 01, biovar cholerae' },
    { code: 'A00.1', desc: 'Cholera due to Vibrio cholerae 01, biovar eltor' },
    { code: 'A01.0', desc: 'Typhoid fever' },
    { code: 'A01.1', desc: 'Paratyphoid fever A' },
    { code: 'A01.2', desc: 'Paratyphoid fever B' },
    { code: 'A01.3', desc: 'Paratyphoid fever C' },
    { code: 'A02.0', desc: 'Salmonella enteritis' },
    { code: 'A03.0', desc: 'Shigellosis due to Shigella dysenteriae' },
    { code: 'A03.1', desc: 'Shigellosis due to Shigella flexneri' },
    { code: 'A03.9', desc: 'Shigellosis, unspecified' },
    { code: 'A04.0', desc: 'Enteropathogenic Escherichia coli infection' },
    { code: 'A04.5', desc: 'Campylobacter enteritis' },
    { code: 'A06.0', desc: 'Acute amebic dysentery' },
    { code: 'A07.1', desc: 'Giardiasis [lambliasis]' },
    { code: 'A08.0', desc: 'Rotaviral enteritis' },
    { code: 'A09', desc: 'Infectious gastroenteritis and colitis' },
    { code: 'A15.0', desc: 'Tuberculosis of lung, confirmed by culture' },
    { code: 'A16.2', desc: 'Tuberculosis of lung, without mention of bacteriological or histological confirmation' },
    { code: 'B20', desc: 'HIV disease' },
    { code: 'B24', desc: 'Unspecified human immunodeficiency virus [HIV] disease' },
    { code: 'B35.0', desc: 'Tinea barbae and tinea capitis' },
    { code: 'B35.1', desc: 'Tinea unguium' },
    { code: 'B35.3', desc: 'Tinea pedis' },
    { code: 'B35.4', desc: 'Tinea corporis' },
    { code: 'B37.0', desc: 'Candidal stomatitis' },
    { code: 'B50.0', desc: 'Plasmodium falciparum malaria with cerebral complications' },
    { code: 'B50.9', desc: 'Plasmodium falciparum malaria, unspecified' },
    { code: 'B54', desc: 'Unspecified malaria' },
    { code: 'C00', desc: 'Malignant neoplasm of lip' },
    { code: 'C22.0', desc: 'Liver cell carcinoma' },
    { code: 'C50.9', desc: 'Malignant neoplasm of breast, unspecified' },
    { code: 'C61', desc: 'Malignant neoplasm of prostate' },
    { code: 'D50.0', desc: 'Iron deficiency anemia secondary to blood loss (chronic)' },
    { code: 'D50.9', desc: 'Iron deficiency anemia, unspecified' },
    { code: 'D57.0', desc: 'Sickle-cell anemia with crisis' },
    { code: 'D57.1', desc: 'Sickle-cell anemia without crisis' },
    { code: 'D64.9', desc: 'Anaemia, unspecified' },
    { code: 'E10.9', desc: 'Type 1 diabetes mellitus without complications' },
    { code: 'E11.9', desc: 'Type 2 diabetes mellitus without complications' },
    { code: 'E14.9', desc: 'Unspecified diabetes mellitus without complications' },
    { code: 'E40', desc: 'Kwashiorkor' },
    { code: 'E41', desc: 'Nutritional marasmus' },
    { code: 'E46', desc: 'Unspecified protein-energy malnutrition' },
    { code: 'E50.9', desc: 'Vitamin A deficiency, unspecified' },
    { code: 'E66.0', desc: 'Obesity due to excess calories' },
    { code: 'E66.9', desc: 'Obesity, unspecified' },
    { code: 'E86', desc: 'Volume depletion' },
    { code: 'F03', desc: 'Unspecified dementia' },
    { code: 'F10.0', desc: 'Mental and behavioral disorders due to use of alcohol, acute intoxication' },
    { code: 'F32.9', desc: 'Depressive episode, unspecified' },
    { code: 'F41.9', desc: 'Anxiety disorder, unspecified' },
    { code: 'G30.9', desc: 'Alzheimer disease, unspecified' },
    { code: 'G40.9', desc: 'Epilepsy, unspecified' },
    { code: 'G43.9', desc: 'Migraine, unspecified' },
    { code: 'G44.2', desc: 'Tension-type headache' },
    { code: 'G47.0', desc: 'Disorders of initiating and maintaining sleep [insomnias]' },
    { code: 'H10.9', desc: 'Conjunctivitis, unspecified' },
    { code: 'H66.9', desc: 'Otitis media, unspecified' },
    { code: 'I10', desc: 'Essential (primary) hypertension' },
    { code: 'I11.0', desc: 'Hypertensive heart disease with (congestive) heart failure' },
    { code: 'I20.9', desc: 'Angina pectoris, unspecified' },
    { code: 'I21.9', desc: 'Acute myocardial infarction, unspecified' },
    { code: 'I25.1', desc: 'Atherosclerotic heart disease' },
    { code: 'I50.9', desc: 'Heart failure, unspecified' },
    { code: 'I64', desc: 'Stroke, not specified as hemorrhage or infarction' },
    { code: 'I84.9', desc: 'Unspecified hemorrhoids without complication' },
    { code: 'J00', desc: 'Acute nasopharyngitis [common cold]' },
    { code: 'J02.9', desc: 'Acute pharyngitis, unspecified' },
    { code: 'J03.9', desc: 'Acute tonsillitis, unspecified' },
    { code: 'J06.9', desc: 'Acute upper respiratory infection, unspecified' },
    { code: 'J11.0', desc: 'Influenza with pneumonia, virus not identified' },
    { code: 'J18.0', desc: 'Bronchopneumonia, unspecified' },
    { code: 'J18.9', desc: 'Pneumonia, unspecified' },
    { code: 'J20.9', desc: 'Acute bronchitis, unspecified' },
    { code: 'J22', desc: 'Unspecified acute lower respiratory infection' },
    { code: 'J44.9', desc: 'Chronic obstructive pulmonary disease, unspecified' },
    { code: 'J45.9', desc: 'Asthma, unspecified' },
    { code: 'K21.9', desc: 'Gastro-oesophageal reflux disease without esophagitis' },
    { code: 'K25.9', desc: 'Gastric ulcer, unspecified as acute or chronic, without hemorrhage or perforation' },
    { code: 'K29.7', desc: 'Gastritis, unspecified' },
    { code: 'K30', desc: 'Dyspepsia' },
    { code: 'K35.8', desc: 'Acute appendicitis, other and unspecified' },
    { code: 'K40.9', desc: 'Unilateral or unspecified inguinal hernia, without obstruction or gangrene' },
    { code: 'K58.0', desc: 'Irritable bowel syndrome with diarrhea' },
    { code: 'K59.0', desc: 'Constipation' },
    { code: 'K70.3', desc: 'Alcoholic cirrhosis of liver' },
    { code: 'K80.2', desc: 'Calculus of gallbladder without cholecystitis' },
    { code: 'L02.9', desc: 'Cutaneous abscess, furuncle and carbuncle, unspecified' },
    { code: 'L03.9', desc: 'Cellulitis, unspecified' },
    { code: 'L20.9', desc: 'Atopic dermatitis, unspecified' },
    { code: 'L50.9', desc: 'Urticaria, unspecified' },
    { code: 'L70.0', desc: 'Acne vulgaris' },
    { code: 'L89.9', desc: 'Decubitus ulcer and pressure area, unspecified' },
    { code: 'M06.9', desc: 'Rheumatoid arthritis, unspecified' },
    { code: 'M10.9', desc: 'Gout, unspecified' },
    { code: 'M15.9', desc: 'Polyarthrosis, unspecified' },
    { code: 'M54.3', desc: 'Sciatica' },
    { code: 'M54.5', desc: 'Low back pain' },
    { code: 'N10', desc: 'Acute tubulo-interstitial nephritis' },
    { code: 'N17.9', desc: 'Acute renal failure, unspecified' },
    { code: 'N18.9', desc: 'Chronic renal failure, unspecified' },
    { code: 'N20.0', desc: 'Calculus of kidney' },
    { code: 'N23', desc: 'Unspecified renal colic' },
    { code: 'N30.0', desc: 'Acute cystitis' },
    { code: 'N39.0', desc: 'Urinary tract infection, site not specified' },
    { code: 'N40', desc: 'Hyperplasia of prostate' },
    { code: 'O00.9', desc: 'Ectopic pregnancy, unspecified' },
    { code: 'O03.9', desc: 'Spontaneous abortion, complete or unspecified, without complication' },
    { code: 'O14.9', desc: 'Preeclampsia, unspecified' },
    { code: 'O15.0', desc: 'Eclampsia in pregnancy' },
    { code: 'O21.0', desc: 'Mild hyperemesis gravidarum' },
    { code: 'O80', desc: 'Single spontaneous delivery' },
    { code: 'O82', desc: 'Delivery by caesarean section' },
    { code: 'P55.0', desc: 'Rh isoimmunization of newborn' },
    { code: 'P58.9', desc: 'Neonatal jaundice due to excessive hemolysis, unspecified' },
    { code: 'R05', desc: 'Cough' },
    { code: 'R10.0', desc: 'Acute abdomen' },
    { code: 'R10.4', desc: 'Other and unspecified abdominal pain' },
    { code: 'R11', desc: 'Nausea and vomiting' },
    { code: 'R50.9', desc: 'Fever, unspecified' },
    { code: 'R51', desc: 'Headache' },
    { code: 'R53', desc: 'Malaise and fatigue' },
    { code: 'S00', desc: 'Superficial injury of head' },
    { code: 'S06.0', desc: 'Concussion' },
    { code: 'S52.9', desc: 'Fracture of forearm, part unspecified' },
    { code: 'S72.9', desc: 'Fracture of femur, part unspecified' },
    { code: 'S82.9', desc: 'Fracture of lower leg, unspecified' },
    { code: 'T14.9', desc: 'Injury, unspecified' },
    { code: 'T78.4', desc: 'Allergy / Anaphylaxis' },
    { code: 'Z00.0', desc: 'General medical examination' },

    // More codes from the PDF...
    { code: 'A05.9', desc: 'Bacterial foodborne intoxication, unspecified' },
    { code: 'A20.9', desc: 'Plague, unspecified' },
    { code: 'A30.9', desc: 'Leprosy, unspecified' },
    { code: 'A35', desc: 'Other tetanus' },
    { code: 'A37.9', desc: 'Whooping cough, unspecified' },
    { code: 'A38', desc: 'Scarlet fever' },
    { code: 'A39.0', desc: 'Meningococcal meningitis' },
    { code: 'A41.9', desc: 'Septicemia, unspecified' },
    { code: 'B00.9', desc: 'Herpesviral infection, unspecified' },
    { code: 'B01.9', desc: 'Varicella without complications' },
    { code: 'B02.9', desc: 'Zoster without complication' },
    { code: 'B05.9', desc: 'Measles without complication' },
    { code: 'B15.9', desc: 'Hepatitis A without hepatic coma' },
    { code: 'B16.9', desc: 'Acute hepatitis B without delta-agent and without hepatic coma' },
    { code: 'B18.2', desc: 'Chronic viral hepatitis C' },
    { code: 'B58.9', desc: 'Toxoplasmosis, unspecified' },
    { code: 'B86', desc: 'Scabies' },
    { code: 'B99', desc: 'Other and unspecified infectious diseases' },
    { code: 'D10.0', desc: 'Benign neoplasm of lip' },
    { code: 'D11.9', desc: 'Benign neoplasm of major salivary gland, unspecified' },
    { code: 'D12.6', desc: 'Benign neoplasm of colon, unspecified' },
    { code: 'D24', desc: 'Benign neoplasm of breast' },
    { code: 'D25.9', desc: 'Leiomyoma of uterus, unspecified' },
    { code: 'D27', desc: 'Benign neoplasm of ovary' },
    { code: 'D29.1', desc: 'Benign neoplasm of prostate' },
    { code: 'E03.9', desc: 'Hypothyroidism, unspecified' },
    { code: 'E04.9', desc: 'Nontoxic goiter, unspecified' },
    { code: 'E27.9', desc: 'Disorder of adrenal gland, unspecified' },
    { code: 'E55.9', desc: 'Vitamin D deficiency, unspecified' },
    { code: 'E78.5', desc: 'Hyperlipidemia, unspecified' },
    { code: 'E87.2', desc: 'Acidosis' },
    { code: 'F20.9', desc: 'Schizophrenia, unspecified' },
    { code: 'F31.9', desc: 'Bipolar affective disorder, unspecified' },
    { code: 'F40.0', desc: 'Agoraphobia' },
    { code: 'F40.1', desc: 'Social phobias' },
    { code: 'F51.0', desc: 'Nonorganic insomnia' },
    { code: 'F54', desc: 'Psychological and behavioral factors associated with disorders or diseases classified elsewhere' },
    { code: 'F90.9', desc: 'Hyperkinetic disorder, unspecified' },
    { code: 'F99', desc: 'Mental disorder, not otherwise specified' },
    { code: 'G40.3', desc: 'Generalized idiopathic epilepsy and epileptic syndromes' },
    { code: 'G43.0', desc: 'Migraine without aura [common migraine]' },
    { code: 'G43.1', desc: 'Migraine with aura [classical migraine]' },
    { code: 'G47.3', desc: 'Sleep apnea' },
    { code: 'G50.0', desc: 'Trigeminal neuralgia' },
    { code: 'G51.0', desc: 'Bell palsy' },
    { code: 'G54.1', desc: 'Lumbosacral plexus disorders' },
    { code: 'H01.0', desc: 'Blepharitis' },
    { code: 'H11.0', desc: 'Pterygium' },
    { code: 'H16.0', desc: 'Corneal ulcer' },
    { code: 'H25.9', desc: 'Senile cataract, unspecified' },
    { code: 'H40.0', desc: 'Glaucoma suspect' },
    { code: 'H40.1', desc: 'Primary open-angle glaucoma' },
    { code: 'H52.1', desc: 'Myopia' },
    { code: 'H52.2', desc: 'Astigmatism' },
    { code: 'H53.6', desc: 'Night blindness' },
    { code: 'H60.0', desc: 'Abscess of external ear' },
    { code: 'H60.1', desc: 'Cellulitis of external ear' },
    { code: 'H61.2', desc: 'Impacted cerumen' },
    { code: 'H90.2', desc: 'Conductive hearing loss, unspecified' },
    { code: 'H91.1', desc: 'Presbycusis' },
    { code: 'H93.1', desc: 'Tinnitus' },
    { code: 'I00', desc: 'Rheumatic fever without mention of heart involvement' },
    { code: 'I05.0', desc: 'Mitral stenosis' },
    { code: 'I10', desc: 'Essential (primary) hypertension' },
    { code: 'I20.0', desc: 'Unstable angina' },
    { code: 'I48', desc: 'Atrial fibrillation and flutter' },
    { code: 'I50.0', desc: 'Congestive heart failure' },
    { code: 'I63.9', desc: 'Cerebral infarction, unspecified' },
    { code: 'I70.9', desc: 'Generalized and unspecified atherosclerosis' },
    { code: 'I73.0', desc: 'Raynaud syndrome' },
    { code: 'I80.9', desc: 'Phlebitis and thrombophlebitis of unspecified site' },
    { code: 'I82.9', desc: 'Embolism and thrombosis of unspecified vein' },
    { code: 'I83.9', desc: 'Varicose veins of lower extremities without ulcer or inflammation' },
    { code: 'I95.9', desc: 'Hypotension, unspecified' },
    { code: 'I99', desc: 'Other and unspecified disorders of circulatory system' },
    { code: 'J01.9', desc: 'Acute sinusitis, unspecified' },
    { code: 'J04.0', desc: 'Acute laryngitis' },
    { code: 'J04.1', desc: 'Acute tracheitis' },
    { code: 'J30.0', desc: 'Vasomotor rhinitis' },
    { code: 'J31.0', desc: 'Chronic rhinitis' },
    { code: 'J32.9', desc: 'Chronic sinusitis, unspecified' },
    { code: 'J33.9', desc: 'Nasal polyp, unspecified' },
    { code: 'J35.0', desc: 'Chronic tonsillitis' },
    { code: 'J40', desc: 'Bronchitis, not specified as acute or chronic' },
    { code: 'J42', desc: 'Unspecified chronic bronchitis' },
    { code: 'J43.9', desc: 'Emphysema, unspecified' },
    { code: 'J44.0', desc: 'Chronic obstructive pulmonary disease with acute lower respiratory infection' },
    { code: 'J44.1', desc: 'Chronic obstructive pulmonary disease with acute exacerbation, unspecified' },
    { code: 'J46', desc: 'Status asthmaticus' },
    { code: 'J47', desc: 'Bronchiectasis' },
    { code: 'J60', desc: 'Coalworker pneumoconiosis' },
    { code: 'J61', desc: 'Pneumoconiosis due to asbestos and other mineral fibers' },
    { code: 'J64', desc: 'Unspecified pneumoconiosis' },
    { code: 'J80', desc: 'Adult respiratory distress syndrome' },
    { code: 'J81', desc: 'Pulmonary edema' },
    { code: 'J90', desc: 'Pleural effusion, not elsewhere classified' },
    { code: 'J96.0', desc: 'Acute respiratory failure' },
    { code: 'J98.4', desc: 'Other disorders of lung' },
    { code: 'K00.0', desc: 'Anodontia' },
    { code: 'K02.9', desc: 'Dental caries, unspecified' },
    { code: 'K04.0', desc: 'Pulpitis' },
    { code: 'K12.0', desc: 'Recurrent oral aphthae' },
    { code: 'K13.0', desc: 'Diseases of lips' },
    { code: 'K20', desc: 'Esophagitis' },
    { code: 'K29.0', desc: 'Acute hemorrhagic gastritis' },
    { code: 'K35.2', desc: 'Acute appendicitis with generalized peritonitis' },
    { code: 'K35.3', desc: 'Acute appendicitis with localized peritonitis' },
    { code: 'K40.0', desc: 'Bilateral inguinal hernia, with obstruction, without gangrene' },
    { code: 'K40.1', desc: 'Bilateral inguinal hernia, with gangrene' },
    { code: 'K59.1', desc: 'Functional diarrhea' },
    { code: 'K63.0', desc: 'Abscess of intestine' },
    { code: 'K65.0', desc: 'Acute peritonitis' },
    { code: 'K70.0', desc: 'Alcoholic fatty liver' },
    { code: 'K70.1', desc: 'Alcoholic hepatitis' },
    { code: 'K76.9', desc: 'Liver disease, unspecified' },
    { code: 'K81.0', desc: 'Acute cholecystitis' },
    { code: 'K82.0', desc: 'Obstruction of gallbladder' },
    { code: 'K83.0', desc: 'Cholangitis' },
    { code: 'K85.9', desc: 'Acute pancreatitis, unspecified' },
    { code: 'K86.1', desc: 'Other chronic pancreatitis' },
    { code: 'K90.0', desc: 'Celiac disease' },
    { code: 'K92.0', desc: 'Hematemesis' },
    { code: 'K92.1', desc: 'Melena' },
    { code: 'K92.9', desc: 'Disease of digestive system, unspecified' },
    { code: 'L01.0', desc: 'Impetigo [any organism] [any site]' },
    { code: 'L02.0', desc: 'Cutaneous abscess, furuncle and carbuncle of face' },
    { code: 'L03.0', desc: 'Cellulitis of finger and toe' },
    { code: 'L03.1', desc: 'Cellulitis of other parts of limb' },
    { code: 'L03.2', desc: 'Cellulitis of face' },
    { code: 'L03.3', desc: 'Cellulitis of trunk' },
    { code: 'L05.0', desc: 'Pilonidal cyst with abscess' },
    { code: 'L08.0', desc: 'Pyoderma' },
    { code: 'L08.1', desc: 'Erythrasma' },
    { code: 'L10.0', desc: 'Pemphigus vulgaris' },
    { code: 'L12.0', desc: 'Bullous pemphigoid' },
    { code: 'L21.0', desc: 'Seborrhea capitis' },
    { code: 'L22', desc: 'Diaper [napkin] dermatitis' },
    { code: 'L23.9', desc: 'Allergic contact dermatitis, unspecified cause' },
    { code: 'L28.0', desc: 'Lichen simplex chronicus' },
    { code: 'L28.1', desc: 'Prurigo nodularis' },
    { code: 'L29.0', desc: 'Pruritus ani' },
    { code: 'L29.1', desc: 'Pruritus scroti' },
    { code: 'L29.2', desc: 'Pruritus vulvae' },
    { code: 'L29.3', desc: 'Anogenital pruritus, unspecified' },
    { code: 'L30.0', desc: 'Nummular dermatitis' },
    { code: 'L30.1', desc: 'Dyshidrosis [pompholyx]' },
    { code: 'L30.9', desc: 'Dermatitis, unspecified' },
    { code: 'L40.0', desc: 'Psoriasis vulgaris' },
    { code: 'L42', desc: 'Pityriasis rosea' },
    { code: 'L50.0', desc: 'Allergic urticaria' },
    { code: 'L55.0', desc: 'Sunburn of first degree' },
    { code: 'L60.0', desc: 'Ingrowing nail' },
    { code: 'L70.0', desc: 'Acne vulgaris' },
    { code: 'L73.0', desc: 'Acne keloid' },
    { code: 'L73.2', desc: 'Hidradenitis suppurativa' },
    { code: 'L74.0', desc: 'Miliaria rubra' },
    { code: 'L75.0', desc: 'Bromhidrosis' },
    { code: 'L80', desc: 'Vitiligo' },
    { code: 'L81.0', desc: 'Postinflammatory hyperpigmentation' },
    { code: 'L81.1', desc: 'Chloasma' },
    { code: 'L81.2', desc: 'Freckles' },
    { code: 'L82', desc: 'Seborrheic keratosis' },
    { code: 'L83', desc: 'Acanthosis nigricans' },
    { code: 'L84', desc: 'Corns and callousities' },
    { code: 'L88', desc: 'Pyoderma gangrenosum' },
    { code: 'L91.0', desc: 'Keloid scar' },
    { code: 'L94.1', desc: 'Linear scleroderma' },
    { code: 'L97', desc: 'Ulcer of lower limb, not elsewhere classified' },
    { code: 'L98.0', desc: 'Pyogenic granuloma' },
    { code: 'M10.0', desc: 'Idiopathic gout' },
    { code: 'M15.0', desc: 'Primary generalized (osteo)arthrosis' },
    { code: 'M20.1', desc: 'Hallux valgus (acquired)' },
    { code: 'M21.4', desc: 'Flat foot [pes planus] (acquired)' },
    { code: 'M25.4', desc: 'Effusion of joint' },
    { code: 'M25.5', desc: 'Pain in joint' },
    { code: 'M30.0', desc: 'Polyarteritis nodosa' },
    { code: 'M32.0', desc: 'Drug-induced systemic lupus erythematosus' },
    { code: 'M33.2', desc: 'Polymyositis' },
    { code: 'M40.0', desc: 'Postural kyphosis' },
    { code: 'M45', desc: 'Ankylosing spondylitis' },
    { code: 'M54.4', desc: 'Lumbago with sciatica' },
    { code: 'M60.0', desc: 'Infective myositis' },
    { code: 'M62.4', desc: 'Contracture of muscle' },
    { code: 'M65.3', desc: 'Trigger finger' },
    { code: 'M67.0', desc: 'Short Achilles tendon (acquired)' },
    { code: 'M70.1', desc: 'Bursitis of hand' },
    { code: 'M70.4', desc: 'Prepatellar bursitis' },
    { code: 'M71.0', desc: 'Abscess of bursa' },
    { code: 'M79.1', desc: 'Myalgia' },
    { code: 'M79.7', desc: 'Fibromyalgia' },
    { code: 'M80.0', desc: 'Postmenopausal osteoporosis with pathological fracture' },
    { code: 'M81.0', desc: 'Postmenopausal osteoporosis' },
    { code: 'M86.0', desc: 'Acute hematogenous osteomyelitis' },
    { code: 'M95.0', desc: 'Acquired deformity of nose' },
    { code: 'N00.0', desc: 'Acute nephritic syndrome, minor glomerular abnormality' },
    { code: 'N04.0', desc: 'Nephrotic syndrome, minor glomerular abnormality' },
    { code: 'N20.1', desc: 'Calculus of ureter' },
    { code: 'N31.0', desc: 'Uninhibited neuropathic bladder, not elsewhere classified' },
    { code: 'N34.0', desc: 'Urethral abscess' },
    { code: 'N34.1', desc: 'Nonspecific urethritis' },
    { code: 'N41.0', desc: 'Acute prostatitis' },
    { code: 'N41.1', desc: 'Chronic prostatitis' },
    { code: 'N41.2', desc: 'Abscess of prostate' },
    { code: 'N46', desc: 'Male infertility' },
    { code: 'N48.1', desc: 'Balanoposthitis' },
    { code: 'N48.3', desc: 'Priapism' },
    { code: 'N50.0', desc: 'Atrophy of testis' },
    { code: 'N60.0', desc: 'Solitary cyst of breast' },
    { code: 'N61', desc: 'Inflammatory disorders of breast' },
    { code: 'N64.4', desc: 'Mastodynia' },
    { code: 'N70.0', desc: 'Acute salpingitis and oophoritis' },
    { code: 'N71.0', desc: 'Acute inflammatory disease of uterus' },
    { code: 'N72', desc: 'Inflammatory disease of cervix uteri' },
    { code: 'N73.0', desc: 'Acute parametritis and pelvic cellulitis' },
    { code: 'N73.3', desc: 'Female acute pelvic peritonitis' },
    { code: 'N75.1', desc: 'Abscess of Bartholin gland' },
    { code: 'N76.0', desc: 'Acute vaginitis' },
    { code: 'N76.2', desc: 'Acute vulvitis' },
    { code: 'N76.4', desc: 'Abscess of vulva' },
    { code: 'N80.0', desc: 'Endometriosis of uterus' },
    { code: 'N81.0', desc: 'Female urethrocele' },
    { code: 'N81.1', desc: 'Cystocele' },
    { code: 'N81.6', desc: 'Rectocele' },
    { code: 'N82.0', desc: 'Vesicovaginal fistula' },
    { code: 'N83.0', desc: 'Follicular cyst of ovary' },
    { code: 'N83.1', desc: 'Corpus luteum cyst' },
    { code: 'N84.0', desc: 'Polyp of corpus uteri' },
    { code: 'N84.1', desc: 'Polyp of cervix uteri' },
    { code: 'N84.2', desc: 'Polyp of vagina' },
    { code: 'N84.3', desc: 'Polyp of vulva' },
    { code: 'N86', desc: 'Erosion and ectropion of cervix uteri' },
    { code: 'N87.0', desc: 'Mild cervical dysplasia' },
    { code: 'N91.0', desc: 'Primary amenorrhea' },
    { code: 'N91.3', desc: 'Primary oligomenorrhea' },
    { code: 'N92.0', desc: 'Excessive and frequent menstruation with regular cycle' },
    { code: 'N92.3', desc: 'Ovulation bleeding' },
    { code: 'N94.1', desc: 'Dyspareunia' },
    { code: 'N94.2', desc: 'Vaginismus' },
    { code: 'N95.0', desc: 'Postmenopausal bleeding' },
    { code: 'N95.1', desc: 'Menopausal and female climacteric states' },
    { code: 'N96', desc: 'Habitual aborter' },
    { code: 'N97.0', desc: 'Female infertility associated with anovulation' },
    { code: 'N98.0', desc: 'Infection associated with artificial insemination' },
    { code: 'O00.1', desc: 'Tubal pregnancy' },
    { code: 'O00.2', desc: 'Ovarian pregnancy' },
    { code: 'O01.0', desc: 'Classical hydatidiform mole' },
    { code: 'O02.1', desc: 'Missed abortion' },
    { code: 'O12.0', desc: 'Gestational edema' },
    { code: 'O12.1', desc: 'Gestational proteinuria' },
    { code: 'O20.0', desc: 'Threatened abortion' },
    { code: 'O21.1', desc: 'Hyperemesis gravidarum with metabolic disturbance' },
    { code: 'O24.0', desc: 'Pre-existing type 1 diabetes mellitus' },
    { code: 'O24.1', desc: 'Pre-existing type 2 diabetes mellitus' },
    { code: 'O30.0', desc: 'Twin pregnancy' },
    { code: 'O40', desc: 'Polyhydramnios' },
    { code: 'O41.0', desc: 'Oligohydramnios' },
    { code: 'O42.0', desc: 'Premature rupture of membranes, onset of labor within 24 hours' },
    { code: 'O44.0', desc: 'Placenta previa specified as without hemorrhage' },
    { code: 'O46.0', desc: 'Antepartum hemorrhage with coagulation defect' },
    { code: 'O60', desc: 'Preterm delivery' },
    { code: 'O85', desc: 'Puerperal sepsis' },
    { code: 'O90.0', desc: 'Disruption of cesarean section wound' },
    { code: 'P00.0', desc: 'Newborn affected by maternal hypertensive disorders' },
    { code: 'P01.0', desc: 'Newborn affected by incompetent cervix' },
    { code: 'P05.0', desc: 'Light for gestational age' },
    { code: 'P07.0', desc: 'Extremely low birthweight' },
    { code: 'P10.0', desc: 'Subdural hemorrhage due to birth injury' },
    { code: 'P11.0', desc: 'Cerebral edema due to birth injury' },
    { code: 'P12.0', desc: 'Cephalhematoma due to birth injury' },
    { code: 'P12.3', desc: 'Bruising of scalp due to birth injury' },
    { code: 'P13.0', desc: 'Fracture of skull due to birth injury' },
    { code: 'P13.2', desc: 'Birth injury to femur' },
    { code: 'P21.0', desc: 'Severe birth asphyxia' },
    { code: 'P21.1', desc: 'Mild and moderate birth asphyxia' },
    { code: 'P22.0', desc: 'Respiratory distress syndrome of newborn' },
    { code: 'P24.0', desc: 'Neonatal aspiration of meconium' },
    { code: 'P35.0', desc: 'Congenital rubella syndrome' },
    { code: 'P36.0', desc: 'Sepsis of newborn due to streptococcus, group B' },
    { code: 'P36.2', desc: 'Sepsis of newborn due to Staphylococcus aureus' },
    { code: 'P38', desc: 'Omphalitis of newborn with or without mild hemorrhage' },
    { code: 'P53', desc: 'Hemorrhagic disease of newborn' },
    { code: 'P54.0', desc: 'Neonatal hematemesis' },
    { code: 'P54.1', desc: 'Neonatal melena' },
    { code: 'P59.0', desc: 'Neonatal jaundice associated with preterm delivery' },
    { code: 'P77', desc: 'Necrotizing enterocolitis of newborn' },
    { code: 'P78.0', desc: 'Perinatal intestinal perforation' },
    { code: 'P90', desc: 'Convulsions of newborn' },
    { code: 'P91.0', desc: 'Neonatal cerebral ischemia' },
    { code: 'Q00.0', desc: 'Anencephaly' },
    { code: 'Q02', desc: 'Microcephaly' },
    { code: 'Q03.9', desc: 'Congenital hydrocephalus, unspecified' },
    { code: 'Q05.9', desc: 'Spina bifida, unspecified' },
    { code: 'Q10.0', desc: 'Congenital ptosis' },
    { code: 'Q11.0', desc: 'Cystic eyeball' },
    { code: 'Q21.0', desc: 'Ventricular septal defect' },
    { code: 'Q21.1', desc: 'Atrial septal defect' },
    { code: 'Q36.0', desc: 'Cleft lip, bilateral' },
    { code: 'Q37.0', desc: 'Cleft hard palate with cleft lip, bilateral' },
    { code: 'Q38.1', desc: 'Ankyloglossia' },
    { code: 'Q53.0', desc: 'Ectopic testis' },
    { code: 'Q61.4', desc: 'Renal dysplasia' },
    { code: 'Q66.0', desc: 'Talipes equinovarus' },
    { code: 'Q87.4', desc: 'Marfan syndrome' },
    { code: 'Q90.0', desc: 'Trisomy 21, meiotic nondisjunction' },
    { code: 'Q90.9', desc: 'Down syndrome, unspecified' },
    { code: 'R05', desc: 'Cough' },
    { code: 'R06.0', desc: 'Dyspnea' },
    { code: 'R10.0', desc: 'Acute abdomen' },
    { code: 'R11', desc: 'Nausea and vomiting' },
    { code: 'R12', desc: 'Heartburn' },
    { code: 'R17', desc: 'Unspecified jaundice' },
    { code: 'R18', desc: 'Ascites' },
    { code: 'R19.6', desc: 'Halitosis' },
    { code: 'R21', desc: 'Rash and other nonspecific skin eruption' },
    { code: 'R23.0', desc: 'Cyanosis' },
    { code: 'R23.1', desc: 'Pallor' },
    { code: 'R23.2', desc: 'Flushing' },
    { code: 'R33', desc: 'Retention of urine' },
    { code: 'R31', desc: 'Unspecified hematuria' },
    { code: 'R35', desc: 'Polyuria' },
    { code: 'R40.0', desc: 'Somnolence' },
    { code: 'R40.1', desc: 'Stupor' },
    { code: 'R42', desc: 'Dizziness and giddiness' },
    { code: 'R45.0', desc: 'Nervousness' },
    { code: 'R50.9', desc: 'Fever, unspecified' },
    { code: 'R51', desc: 'Headache' },
    { code: 'R53', desc: 'Malaise and fatigue' },
    { code: 'R64', desc: 'Cachexia' },
    { code: 'R70.0', desc: 'Elevated erythrocyte sedimentation rate' },
    { code: 'R80', desc: 'Isolated proteinuria' },
    { code: 'R81', desc: 'Glycosuria' },
    { code: 'R95', desc: 'Sudden infant death syndrome' },
    { code: 'S00.0', desc: 'Superficial injury of scalp' },
    { code: 'S01.0', desc: 'Open wound of scalp' },
    { code: 'S02.0', desc: 'Fracture of vault of skull' },
    { code: 'S03.0', desc: 'Dislocation of jaw' },
    { code: 'S06.0', desc: 'Concussion' },
    { code: 'S10.0', desc: 'Contusion of throat' },
    { code: 'S52.0', desc: 'Fracture of upper end of ulna' },
    { code: 'S52.1', desc: 'Fracture of upper end of radius' },
    { code: 'S60.0', desc: 'Contusion of finger(s) without damage to nail' },
    { code: 'S61.0', desc: 'Open wound of finger(s) without damage to nail' },
    { code: 'S63.1', desc: 'Dislocation of finger' },
    { code: 'S72.0', desc: 'Fracture of neck of femur' },
    { code: 'S82.0', desc: 'Fracture of patella' },
    { code: 'S86.0', desc: 'Injury of Achilles tendon' },
    { code: 'S90.0', desc: 'Contusion of ankle' },
    { code: 'S93.1', desc: 'Dislocation of toe(s)' },
    { code: 'T15.0', desc: 'Foreign body in cornea' },
    { code: 'T16', desc: 'Foreign body in ear' },
    { code: 'T18.0', desc: 'Foreign body in mouth' },
    { code: 'T30.0', desc: 'Burn of unspecified body region, unspecified degree' },
    { code: 'T33.0', desc: 'Superficial frostbite of head' },
    { code: 'T71', desc: 'Asphyxiation' },
    { code: 'T78.4', desc: 'Allergy / Anaphylaxis' },
    { code: 'T81.4', desc: 'Infection following a procedure, not elsewhere classified' },
    { code: 'U07.1', desc: 'COVID-19' }
];
